### ISSUE TITLE
Entering search bar causes issues 

### ISSUE THREAD

**Issue by 5PIterator** [jaredlll08/Controlling#206] opened 2024-10-31 15:20 UTC
When you enter the search bar, you can't leave it, making each key stroke being directed to it. This makes multiple binds impossible, including clearing the bind. 
The only workaround is changing Full-screen.

Fabric 1.18.2 9.0+23

**Comment by hacker-on-steroids** [comment] 2024-11-17 19:40
+1
a qol mod having insanely negative downsides feels wrong

**Comment by jaredlll08** [comment] 2024-11-17 22:33
I'm unable to reproduce this at all, using:
```
controlling 9.0+23
fabric-api 0.77.0+1.18.2
fabricloader 0.16.9
minecraft 1.18.2
searchables 1.0.1
java 17
```
Can you reproduce it with *just* `controlling`, `fabric-api` and `searchables`?

**Comment by 5PIterator** [comment] 2024-11-18 10:31
> I'm unable to reproduce this at all, using:
> 
> ```
> controlling 9.0+23
> fabric-api 0.77.0+1.18.2
> fabricloader 0.16.9
> minecraft 1.18.2
> searchables 1.0.1
> java 17
> ```
> 
> Can you reproduce it with _just_ `controlling`, `fabric-api` and `searchables`?

Sorry for not clarifying, I encountered this issue in the modpack Create Astral 2.1.2. (1.18.2)

As instructed, I removed all mods except for 'controlling' and 'fabric-api', and added 'searchables'. The issue has disappeared, except for the ability to bind multiple keys.

**Comment by hacker-on-steroids** [comment] 2024-11-18 15:22
there's no rain sound either so i'm gonna go with "packdevs are idorts and broke lots of shit"

**Comment by jaredlll08** [comment] 2024-11-18 17:12
Yea... I'm going to be closing this.

>except for the ability to bind multiple keys.

This has never been a feature of Controlling, another mod would have had to add it.

Also needless to say, Controlling does not touch rain sounds, so I am going to assume that modpack has other mods that are interfering with things.

**Closed as not planned by jaredlll08** 2024-11-18 17:12 UTC

**Comment by drakosoldier298** [comment] 2025-04-03 17:51
I know this was closed but i am curious if the mod causing issue was found as i have encountered this on 1.21.5

**Comment by drakosoldier298** [comment] 2025-04-04 00:55
For anyone in the future, For me it was client commands
