### ISSUE TITLE
Support for Amecs

### ISSUE THREAD

**Issue by jeytee84** [jaredlll08/Controlling#141] opened 2023-04-03 18:25 UTC
I've seen some outdated feature request but the issue of compatibility is still not resolved. Are there any solutions I don't know about to use both modifier keys and search?

**Comment by jaredlll08** [comment] 2023-07-18 18:06
Duplicate of https://github.com/jaredlll08/Controlling/issues/77

I would like them to be supported and have even gone out of my way to add events that other mods can use to ensure there is support, but I tried reaching out to Siphalor in the linked issue and have gotten no reply.

The only way this is going to get support is if Siphalor adds code to Amecs.

**Closed by jaredlll08** 2023-07-18 18:06 UTC
