### ISSUE TITLE
Major issue

### ISSUE THREAD

**Issue by SeanDaBitch** [jaredlll08/Controlling#98] opened 2021-11-13 03:13 UTC
![IMG_5111](https://user-images.githubusercontent.com/93109251/141603751-f01ce336-6575-4826-8b97-7e261377de16.jpg)
Whatever the fuck this is

**Comment by jaredlll08** [comment] 2021-11-13 11:07
Mc version?

controlling version?

What language is your game set to?

**Comment by SeanDaBitch** [comment] 2021-11-15 07:08
English (US)
1.8.9 forge (no mods installed) 
Latest 1.8.9 controlling version

**Comment by jaredlll08** [comment] 2021-11-16 00:14
Duplicate of #90.

I can't even setup a 1.12 workspace let alone a 18.9 workspace.

**Closed by jaredlll08** 2021-11-16 00:14 UTC
