### ISSUE TITLE
[Feature Request] Ability to use Alt-Control-Shift combination with other keys

### ISSUE THREAD

**Issue by EGOIST1372** [jaredlll08/Controlling#135] opened 2023-01-29 13:31 UTC
Ability to use Alt-Control-Shift combination with other keys like adding control+f for toggling auto jump or alt+v for changing camera perspective in camera util mod and many more examples
there is a mod called [amecs](https://www.curseforge.com/minecraft/mc-mods/amecs) that has these features but is incompatible with controlling so I can't use it and I like controlling's features more than amec's
so it would be great to add these features to controlling since many people use this mod and the dev of the amecs not fixing the compatibility issue [since forever](https://github.com/Siphalor/amecs/issues/49) 
thanks in advance <3

**Comment by jaredlll08** [comment] 2023-01-29 13:44
Duplicate of https://github.com/jaredlll08/Controlling/issues/77

**Closed by jaredlll08** 2023-01-29 13:44 UTC
