### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SeanDaBitch** [jaredlll08/Controlling#99] opened 2021-11-16 03:31 UTC
Will this bug be fixed: https://i.imgur.com/UbdxSwA.png

**Comment by SeanDaBitch** [comment] 2021-11-16 03:33
I'm running forge 1.8.9
I am using Controlling-7.0.0.2
I tried the mod both with and without other mods and it still has this glitch

**Comment by jaredlll08** [comment] 2021-11-16 06:50
Duplicate of https://github.com/jaredlll08/Controlling/issues/98

NO.

As I said in that issue, I can't setup a 1.8.9 workspace even if I wanted to.

Forge made changes to their maven that broke older versions.

**Closed by jaredlll08** 2021-11-16 06:50 UTC
