### ISSUE TITLE
Crash when opening controls menu

### ISSUE THREAD

**Issue by Stephenator0316** [jaredlll08/Controlling#11] opened 2017-06-18 02:37 UTC
Appears to be Controlling causing it, but I'm not 100% sure. Correct me if I'm wrong, please!

[net.minecraft.init.Bootstrap:func_179870_a:552]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-94.jar)
  LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  BlurPlugin (Blur-1.0.2-10.jar)
  Default Options (DefaultOptions_1.12-9.2.1.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b89.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 6/17/17 10:29 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.client.settings.KeyBinding.compareTo(KeyBinding.java:154)
	at net.minecraft.client.settings.KeyBinding.compareTo(KeyBinding.java:14)
	at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:258)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:203)
	at java.util.Arrays.sort(Arrays.java:1246)
	at us.getfluxed.controlsearch.client.gui.GuiNewKeyBindingList.<init>(GuiNewKeyBindingList.java:32)
	at us.getfluxed.controlsearch.client.gui.GuiNewControls.func_73866_w_(GuiNewControls.java:50)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
	at net.minecraft.client.gui.GuiOptions.func_146284_a(SourceFile:152)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1752)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.settings.KeyBinding.compareTo(KeyBinding.java:154)
	at net.minecraft.client.settings.KeyBinding.compareTo(KeyBinding.java:14)
	at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:258)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:203)
	at java.util.Arrays.sort(Arrays.java:1246)
	at us.getfluxed.controlsearch.client.gui.GuiNewKeyBindingList.<init>(GuiNewKeyBindingList.java:32)
	at us.getfluxed.controlsearch.client.gui.GuiNewControls.func_73866_w_(GuiNewControls.java:50)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
	at net.minecraft.client.gui.GuiOptions.func_146284_a(SourceFile:152)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: us.getfluxed.controlsearch.client.gui.GuiNewControls

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Turtlenator'/2438, l='MpServer', x=-133.89, y=68.00, z=250.09]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-144,64,252), Chunk: (at 0,4,12 in -9,15; contains blocks -144,0,240 to -129,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 746 game time, 746 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 94 total; [EntitySkeleton['Skeleton'/3840, l='MpServer', x=-172.48, y=35.00, z=251.53], EntityCreeper['Creeper'/3848, l='MpServer', x=-204.50, y=61.00, z=228.50], EntityZombie['Zombie'/2825, l='MpServer', x=-210.50, y=31.00, z=279.50], EntityCreeper['Creeper'/3849, l='MpServer', x=-205.50, y=61.00, z=227.50], EntityEnderman['Enderman'/2835, l='MpServer', x=-80.73, y=46.00, z=227.50], EntityRabbit['Rabbit'/275, l='MpServer', x=-59.86, y=68.00, z=199.49], EntityZombie['Zombie'/3860, l='MpServer', x=-210.50, y=40.00, z=282.50], EntityZombie['Zombie'/3605, l='MpServer', x=-139.50, y=49.00, z=189.50], EntityRabbit['Rabbit'/280, l='MpServer', x=-56.23, y=64.00, z=257.80], EntityZombie['Zombie'/3614, l='MpServer', x=-192.50, y=31.00, z=258.50], EntityBat['Bat'/2846, l='MpServer', x=-115.03, y=30.03, z=175.63], EntityZombie['Zombie'/3125, l='MpServer', x=-148.50, y=40.00, z=269.50], EntityZombie['Zombie'/2871, l='MpServer', x=-144.50, y=51.00, z=221.50], EntityCreeper['Creeper'/2874, l='MpServer', x=-117.50, y=30.00, z=172.50], EntitySkeleton['Skeleton'/3645, l='MpServer', x=-107.50, y=28.00, z=304.50], EntitySkeleton['Skeleton'/3646, l='MpServer', x=-106.50, y=28.00, z=302.50], EntityCreeper['Creeper'/3654, l='MpServer', x=-138.50, y=15.00, z=279.50], EntityZombie['Zombie'/3401, l='MpServer', x=-100.50, y=25.00, z=312.50], EntitySkeleton['Skeleton'/3158, l='MpServer', x=-134.50, y=43.00, z=276.50], EntityCreeper['Creeper'/3159, l='MpServer', x=-87.50, y=22.00, z=291.50], EntitySquid['Squid'/2652, l='MpServer', x=-78.92, y=61.16, z=262.72], EntitySquid['Squid'/2653, l='MpServer', x=-76.97, y=59.03, z=270.25], EntitySquid['Squid'/2654, l='MpServer', x=-79.60, y=58.62, z=264.73], EntityCreeper['Creeper'/3424, l='MpServer', x=-117.90, y=49.00, z=277.13], EntitySkeleton['Skeleton'/3168, l='MpServer', x=-55.50, y=14.00, z=177.50], EntityCreeper['Creeper'/3425, l='MpServer', x=-117.47, y=54.00, z=275.83], EntityCreeper['Creeper'/3433, l='MpServer', x=-149.50, y=24.00, z=307.50], EntityBat['Bat'/2683, l='MpServer', x=-164.57, y=25.10, z=220.44], EntitySkeleton['Skeleton'/2687, l='MpServer', x=-207.50, y=22.00, z=212.50], EntityZombie['Zombie'/3711, l='MpServer', x=-136.50, y=37.00, z=301.50], EntitySkeleton['Skeleton'/3457, l='MpServer', x=-197.50, y=32.00, z=262.50], EntityPlayerSP['Turtlenator'/2438, l='MpServer', x=-133.89, y=68.00, z=250.09], EntityBat['Bat'/2951, l='MpServer', x=-148.59, y=37.69, z=303.47], EntityBat['Bat'/2955, l='MpServer', x=-168.99, y=19.23, z=222.01], EntityCreeper['Creeper'/3984, l='MpServer', x=-176.50, y=60.00, z=265.50], EntitySkeleton['Skeleton'/3985, l='MpServer', x=-177.50, y=60.00, z=263.50], EntityZombie['Zombie'/3730, l='MpServer', x=-175.49, y=60.00, z=265.21], EntityCreeper['Creeper'/3738, l='MpServer', x=-191.50, y=20.00, z=239.50], EntityCreeper['Creeper'/3739, l='MpServer', x=-193.50, y=20.00, z=239.50], EntityZombie['Zombie'/3740, l='MpServer', x=-194.50, y=20.00, z=241.50], EntityBat['Bat'/2973, l='MpServer', x=-146.50, y=15.00, z=197.49], EntitySquid['Squid'/2718, l='MpServer', x=-130.39, y=61.27, z=277.15], EntityBat['Bat'/2974, l='MpServer', x=-123.18, y=47.46, z=328.49], EntitySquid['Squid'/2719, l='MpServer', x=-129.33, y=61.00, z=283.01], EntitySquid['Squid'/2720, l='MpServer', x=-129.39, y=62.32, z=285.32], EntitySquid['Squid'/2721, l='MpServer', x=-135.98, y=61.61, z=284.81], EntitySpider['Spider'/2468, l='MpServer', x=-188.50, y=33.00, z=259.50], EntitySkeleton['Skeleton'/2472, l='MpServer', x=-189.50, y=17.00, z=230.50], EntityZombie['Zombie'/2986, l='MpServer', x=-122.50, y=27.00, z=270.50], EntityZombie['Zombie'/2987, l='MpServer', x=-124.50, y=27.00, z=269.50], EntityZombie['Zombie'/2988, l='MpServer', x=-125.50, y=27.00, z=267.50], EntitySkeleton['Skeleton'/3244, l='MpServer', x=-151.50, y=23.00, z=308.50], EntityZombie['Zombie'/2989, l='MpServer', x=-129.50, y=27.00, z=268.50], EntityPig['Pig'/181, l='MpServer', x=-168.50, y=63.00, z=192.50], EntityPig['Pig'/182, l='MpServer', x=-168.50, y=63.00, z=193.50], EntityPig['Pig'/183, l='MpServer', x=-169.50, y=66.00, z=194.50], EntityPig['Pig'/184, l='MpServer', x=-169.50, y=76.00, z=190.50], EntityChicken['Chicken'/185, l='MpServer', x=-177.50, y=69.00, z=256.50], EntityChicken['Chicken'/186, l='MpServer', x=-178.50, y=69.00, z=258.50], EntityChicken['Chicken'/187, l='MpServer', x=-176.50, y=69.00, z=260.50], EntityChicken['Chicken'/188, l='MpServer', x=-177.50, y=69.00, z=262.50], EntityBat['Bat'/2751, l='MpServer', x=-104.56, y=38.49, z=278.56], EntityBat['Bat'/2752, l='MpServer', x=-102.33, y=52.83, z=239.45], EntityZombie['Zombie'/2497, l='MpServer', x=-210.50, y=61.00, z=230.50], EntityZombie['Zombie'/2498, l='MpServer', x=-208.50, y=61.00, z=228.50], EntityZombie['Zombie'/3524, l='MpServer', x=-160.50, y=37.00, z=213.50], EntityZombie['Zombie'/3525, l='MpServer', x=-162.50, y=37.00, z=211.50], EntityZombie['Zombie'/3526, l='MpServer', x=-160.50, y=37.00, z=212.50], EntityPig['Pig'/201, l='MpServer', x=-131.79, y=68.00, z=251.51], EntityBat['Bat'/2505, l='MpServer', x=-141.21, y=51.10, z=222.61], EntityPig['Pig'/202, l='MpServer', x=-134.23, y=67.00, z=249.40], EntityPig['Pig'/203, l='MpServer', x=-137.50, y=69.00, z=253.45], EntityPig['Pig'/204, l='MpServer', x=-140.96, y=67.00, z=255.59], EntityZombie['Zombie'/2522, l='MpServer', x=-101.50, y=46.00, z=266.50], EntityCow['Cow'/227, l='MpServer', x=-107.50, y=71.00, z=178.50], EntitySkeleton['Skeleton'/2531, l='MpServer', x=-121.29, y=30.00, z=253.50], EntityCow['Cow'/228, l='MpServer', x=-106.50, y=71.00, z=177.50], EntityCow['Cow'/229, l='MpServer', x=-107.50, y=71.00, z=180.50], EntityCreeper['Creeper'/3557, l='MpServer', x=-153.50, y=48.00, z=189.50], EntityCow['Cow'/230, l='MpServer', x=-107.50, y=71.00, z=181.50], EntityCow['Cow'/231, l='MpServer', x=-105.50, y=72.00, z=190.50], EntityBat['Bat'/2535, l='MpServer', x=-71.25, y=49.03, z=223.25], EntityCow['Cow'/232, l='MpServer', x=-105.50, y=72.00, z=192.50], EntityCow['Cow'/233, l='MpServer', x=-104.50, y=71.00, z=190.50], EntityCow['Cow'/234, l='MpServer', x=-104.50, y=71.00, z=189.50], EntityCow['Cow'/240, l='MpServer', x=-94.50, y=64.00, z=321.50], EntityCreeper['Creeper'/3312, l='MpServer', x=-87.50, y=53.00, z=235.50], EntityCow['Cow'/241, l='MpServer', x=-97.50, y=64.00, z=321.50], EntityZombie['Zombie'/3313, l='MpServer', x=-91.50, y=53.00, z=241.50], EntityCow['Cow'/242, l='MpServer', x=-98.50, y=64.00, z=324.50], EntityCow['Cow'/243, l='MpServer', x=-107.19, y=67.00, z=326.46], EntityZombie['Zombie'/3062, l='MpServer', x=-147.50, y=37.00, z=275.50], EntityZombie['Zombie'/3063, l='MpServer', x=-149.50, y=37.00, z=274.50], EntityBat['Bat'/2552, l='MpServer', x=-117.61, y=29.40, z=321.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2732)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3149424392 bytes (3003 MB) / 5775032320 bytes (5507 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m -Xms2G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.40 Powered by Forge 14.21.0.2322 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.0.2322.jar) 
	UCHIJAAAA	forge{14.21.0.2322} [Minecraft Forge] (forge-1.12-14.21.0.2322.jar) 
	UCHIJAAAA	aroma1997core{1.3.0.0.b89} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b89.jar) 
	UCHIJAAAA	thedragonlib{1.12-4.0.0} [TheDragonLib] (thedragonlib-1.12-4.0.0.jar) 
	UCHIJAAAA	armorplus{1.12-11.0.0.1-alpha} [ArmorPlus] (armorplus-1.12-11.0.0.1.jar) 
	UCHIJAAAA	aroma1997corehelper{1.3.0.0.b89} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b89.jar) 
	UCHIJAAAA	aroma1997sdimension{1.3.0.0.b34} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b34.jar) 
	UCHIJAAAA	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHIJAAAA	atmlib{1.1.0} [ATM Lib] (atmlib-1.1.0.jar) 
	UCHIJAAAA	quark{r1.2-94} [Quark] (Quark-r1.2-94.jar) 
	UCHIJAAAA	autoreglib{1.2-6} [AutoRegLib] (AutoRegLib-1.2-6.jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2257} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2257-universal.jar) 
	UCHIJAAAA	blur{1.0.2-10} [Blur] (Blur-1.0.2-10.jar) 
	UCHIJAAAA	chameleon{1.12-4.0.0} [Chameleon] (Chameleon-1.12-4.0.0.jar) 
	UCHIJAAAA	nmmlib{1.0.0} [NoMansLib] (NMMLib-1.0.2.1.jar) 
	UCHIJAAAA	computercraft{1.12-1.82pr5} [Computality] (computality-1.12-1.82pr5.jar) 
	UCHIJAAAA	controlling{3.0.0} [Controlling] (Controlling-3.0.0.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.12-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.12-v1.jar) 
	UCHIJAAAA	craftingtweaks{8.1.1} [Crafting Tweaks] (CraftingTweaks_1.12-8.1.1.jar) 
	UCHIJAAAA	custommainmenu{2.0.6} [Custom Main Menu] (CustomMainMenu-MC1.12-2.0.6.jar) 
	UCHIJAAAA	defaultoptions{9.2.1} [Default Options] (DefaultOptions_1.12-9.2.1.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.0.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.0.jar) 
	UCHIJAAAA	gravestone{1.8.0} [Gravestone Mod] (gravestone-1.8.0.jar) 
	UCHIJAAAA	harvest{1.12-1.2.1-13} [Harvest] (Harvest-1.12-1.2.1-13.jar) 
	UCHIJAAAA	jei{4.6.0.61} [Just Enough Items] (jei_1.12-4.6.0.61.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.6b1} [JourneyMap] (journeymap-1.12-5.4.6b1.jar) 
	UCHIJAAAA	jeresources{0.7.0.10} [Just Enough Resources] (JustEnoughResources-1.12-0.7.0.10.jar) 
	UCHIJAAAA	modnametooltip{1.8.0} [Mod Name Tooltip] (modnametooltip_1.12-1.8.0.jar) 
	UCHIJAAAA	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCHIJAAAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UCHIJAAAA	packetfilter{1.5.0} [Packet Filter] (packetfilter-1.6.0.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHIJAAAA	reauth{3.5.0} [ReAuth] (ReAuth-3.5.0.jar) 
	UCHIJAAAA	refinedstorage{1.5} [Refined Storage] (refinedstorage-1.5.jar) 
	UCHIJAAAA	resourceloader{1.5.2} [Resource Loader] (ResourceLoader-MC1.12-1.5.2.jar) 
	UCHIJAAAA	simplesponge{3.1} [Simple Sponge] (simplesponge-1.12-3.1.jar) 
	UCHIJAAAA	soulshardstow{1.12-2.7.0-49} [Soul Shards - The Old Ways] (SoulShards-TOW-1.12-2.7.0-49.jar) 
	UCHIJAAAA	storagedrawers{1.12-5.0.2} [Storage Drawers] (StorageDrawers-1.12-5.0.2.jar) 
	UCHIJAAAA	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.0.0.jar) 
	UCHIJAAAA	theoneprobe{1.4.7} [The One Probe] (theoneprobe-1.2-1.4.7.jar) 
	UCHIJAAAA	traverse{1.12-1.1.2-2} [Traverse] (Traverse-1.12-1.1.2-2.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-94.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  lumien.resourceloader.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
BlurPlugin (Blur-1.0.2-10.jar)
  com.tterrag.blur.BlurTransformer
Default Options (DefaultOptions_1.12-9.2.1.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b89.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.53' Renderer: 'GeForce 940M/PCIe/SSE2'
	Launched Version: forge-14.21.0.2322
	LWJGL: 2.9.4
	OpenGL: GeForce 940M/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

**Comment by jaredlll08** [comment] 2017-06-18 03:00
I believe that you have a mod that registered it's keybindings incorrectly
can you give me your options.txt?

**Comment by Stephenator0316** [comment] 2017-06-18 03:07
version:1139
invertYMouse:false
mouseSensitivity:0.5
fov:0.0
gamma:1.0
saturation:0.0
renderDistance:12
guiScale:3
particles:0
bobView:true
anaglyph3d:false
maxFps:120
fboEnable:true
difficulty:2
fancyGraphics:true
ao:2
renderClouds:true
resourcePacks:[]
incompatibleResourcePacks:[]
lastServer:
lang:en_us
chatVisibility:0
chatColors:true
chatLinks:true
chatLinksPrompt:true
chatOpacity:1.0
snooperEnabled:true
fullscreen:false
enableVsync:true
useVbo:true
hideServerAddress:false
advancedItemTooltips:false
pauseOnLostFocus:true
touchscreen:false
overrideWidth:0
overrideHeight:0
heldItemTooltips:true
chatHeightFocused:1.0
chatHeightUnfocused:0.44366196
chatScale:1.0
chatWidth:1.0
mipmapLevels:4
forceUnicodeFont:false
reducedDebugInfo:false
useNativeTransport:true
entityShadows:true
mainHand:right
attackIndicator:1
showSubtitles:true
realmsNotifications:true
enableWeakAttacks:false
autoJump:true
narrator:0
tutorialStep:none
key_key.attack:-100
key_key.use:-99
key_key.forward:17
key_key.left:30
key_key.back:31
key_key.right:32
key_key.jump:57
key_key.sneak:42
key_key.sprint:29
key_key.drop:16
key_key.inventory:18
key_key.chat:20
key_key.playerlist:15
key_key.pickItem:-98
key_key.command:53
key_key.screenshot:60
key_key.togglePerspective:63
key_key.smoothCamera:0
key_key.fullscreen:87
key_key.spectatorOutlines:0
key_key.swapHands:33
key_key.saveToolbarActivator:46
key_key.loadToolbarActivator:45
key_key.advancements:38
key_key.hotbar.1:2
key_key.hotbar.2:3
key_key.hotbar.3:4
key_key.hotbar.4:5
key_key.hotbar.5:6
key_key.hotbar.6:7
key_key.hotbar.7:8
key_key.hotbar.8:9
key_key.hotbar.9:10
key_quark.keybind.emote.wave:0
key_quark.keybind.emote.salute:0
key_quark.keybind.emote.yes:0
key_quark.keybind.emote.no:0
key_quark.keybind.emote.cheer:0
key_quark.keybind.emote.clap:0
key_quark.keybind.emote.point:0
key_quark.keybind.emote.shrug:0
key_quark.keybind.emote.facepalm:0
key_quark.keybind.emote.headbang:0
key_quark.keybind.toggleAutojump:48
key_quark.keybind.lockBuilding:38
key_quark.keybind.dropoff:0
key_quark.keybind.changeHotbar:45
key_quark.keybind.chestSort:0
key_quark.keybind.chestDropoff:0
key_quark.keybind.chestMerge:0
key_quark.keybind.chestRestock:0
key_quark.keybind.playerSort:0
key_cos.key.openCosArmorInventory:46
key_key.ftbu.guide:0
key_key.ftbu.warp:0
key_key.craftingtweaks.rotate:19
key_key.craftingtweaks.balance:48
key_key.craftingtweaks.clear:46
key_key.craftingtweaks.toggleButtons:0
key_key.craftingtweaks.compressOne:37:CONTROL
key_key.craftingtweaks.compressStack:37
key_key.craftingtweaks.compressAll:37:SHIFT
key_key.craftingtweaks.decompressOne:0
key_key.craftingtweaks.decompressStack:0
key_key.craftingtweaks.decompressAll:0
key_key.craftingtweaks.refill_last:15
key_key.jei.toggleOverlay:24:CONTROL
key_key.jei.focusSearch:33:CONTROL
key_key.jei.showRecipe:19
key_key.jei.showUses:22
key_key.jei.recipeBack:14
key_key.jei.toggleCheatMode:0
key_key.jei.previousPage:201
key_key.jei.nextPage:209
key_key.refinedstorage.focusSearchBar:15
key_key.toggleLiquids:38
key_key.toggleVisible:0
key_key.journeymap.map_toggle:36
key_key.journeymap.zoom_in:13
key_key.journeymap.zoom_out:12
key_key.journeymap.minimap_type:27
key_key.journeymap.minimap_type:27
key_key.journeymap.minimap_preset:43
key_key.journeymap.create_waypoint:48
soundCategory_master:1.0
soundCategory_music:0.0
soundCategory_record:1.0
soundCategory_weather:1.0
soundCategory_block:1.0
soundCategory_hostile:1.0
soundCategory_neutral:1.0
soundCategory_player:1.0
soundCategory_ambient:1.0
soundCategory_voice:1.0
modelPart_cape:true
modelPart_jacket:true
modelPart_left_sleeve:true
modelPart_right_sleeve:true
modelPart_left_pants_leg:true
modelPart_right_pants_leg:true
modelPart_hat:true

**Comment by jaredlll08** [comment] 2017-06-18 03:19
hhm, I got no idea, what are you trying to do? like when does it crash?

**Comment by Stephenator0316** [comment] 2017-06-18 10:47
The moment I click on the "Controls" option in the settings menu

**Comment by SnowShock35** [comment] 2017-06-29 11:10
This isn't an issue with Controlling. The issue is present with Forge and any mod that adds a key binding in that specific version of Forge. It was fixed in build 2324 See the 3 line of this file http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.0.2324/forge-1.12-14.21.0.2324-changelog.txt.

**Comment by SnowShock35** [comment] 2017-06-29 11:10
@jaredlll08 ^

**Closed** 2017-06-29 11:14 UTC
