### ISSUE TITLE
Can't Unbind Actions and Changing Keybind Types In Searchbar - 1.18.2-9.0+23

### ISSUE THREAD

**Issue by Zatchary** [jaredlll08/Controlling#168] opened 2023-11-19 00:49 UTC
In Vanilla Minecraft, you can unbind an action with the escape key. However, with Controlling installed (I'm using version 1.18.2-9.0+23), the escape key does nothing.

Additionally, if you search for a keybind and then change a keybind, as the search bar still thinks you are typing, it will edit the text in the searchbox, which, while not terrible, is mildly inconvinient.

(I'm new to GitHub, so if I made this comment wrong, let me know).

**Comment by jaredlll08** [comment] 2023-11-19 01:08
Can you try and reproduce this with just Controlling installed?

Both issues you have mentioned are things that I have specifically tested for before and would not have left in, so I'm wondering if it is a mod interaction.

**Comment by ProgrammingMaestro** [comment] 2023-12-18 09:08
I've been having the same issue with the same version of the mod (1.18.2-9.0+23). I just swapped to version 9.0+22, and the ESC not working is fixed, although typing on the searchbox while trying to change keybind still occurs.

**Comment by jaredlll08** [comment] 2023-12-18 09:25
@ProgrammingMaestro please can you just edit your whole comment explaining the issue you are currently running into, with your edit2 I do not know if you are even experiencing an issue anymore?

**Comment by ProgrammingMaestro** [comment] 2023-12-19 21:31
> @ProgrammingMaestro please can you just edit your whole comment explaining the issue you are currently running into, with your edit2 I do not know if you are even experiencing an issue anymore?

The problem primarily lies with the search bar. Once selected, it fails to deselect itself after usage. Consequently, when you search for a bind and attempt to use the "esc" key, it doesn't do nothing because the system believes you are still in the search bar. However, if you navigate to the controls menu without interacting with the search bar, scroll to the desired bind, and proceed to unbind it, the issue can be circumvented.

**Comment by jaredlll08** [comment] 2023-12-19 21:48
Thanks, do you have any other mods installed / can you reproduce this with just Controlling and Searchables?

**Comment by ProgrammingMaestro** [comment] 2023-12-20 22:01
> Thanks, do you have any other mods installed / can you reproduce this with just Controlling and Searchables?

No, with only these two mods it works as it should. This probably means that there's a mod conflict. but this will be hard to diagnose since in that other instance I have 320 mods currently

**Comment by jaredlll08** [comment] 2023-12-21 02:30
If you can't reproduce with just Controlling, then there is not much I can do to debug it.

My suggestion would be to start removing mods until it starts working, once you know what mod is causing it, I can see what is going on from there.

**Comment by jaredlll08** [comment] 2024-04-22 22:43
Closing due to no reply and no one else reporting similar.

**Closed by jaredlll08** 2024-04-22 22:43 UTC
