### ISSUE TITLE
[1.20.2] Mod Version 10.0 Crashes upon opening Keybinds Menu

### ISSUE THREAD

**Issue by Nidalfr** [jaredlll08/Controlling#163] opened 2023-10-02 10:26 UTC
Modpack (Fantasy MC) Crashes when opening Keybinds Menu while ingame.
[crash-2023-10-02_12.17.10-client.txt](https://github.com/jaredlll08/Controlling/files/12781844/crash-2023-10-02_12.17.10-client.txt)

**Comment by jaredlll08** [comment] 2023-10-02 10:36
You say 1.20.2, but your log mentions 1.19?

What version are you using exactly?

And can you reproduce with just controlling?

**Comment by Nidalfr** [comment] 2023-10-02 10:40
Sorry,changed modpack recently. it's 1.19.2

**Comment by jaredlll08** [comment] 2023-10-02 10:53
can you reproduce with just controlling?

**Comment by ChiefLogan3010** [comment] 2023-10-09 19:42
I had the same issue on Forge 1.19.2 and thought based on the latest.log that it came from Controlling. However after doing a binary search I narrowed it down to Ny's Wearable Backpacks and found comments on the mod page of others experiencing the same. All that to say, I don't think controlling is actually the issue here, it's just showing up in the log because it changes the keybind screen. I'd recommend doing a binary search yourself to narrow down which mod is causing it in your case. If you don't know what that is, it's essentially disabling half your mods to see if the issue persists, if it does then disable half of what remains and so on.

**Comment by jaredlll08** [comment] 2024-01-03 20:32
Closing due to no reply.

Feel free to re-open this issue if you are still experiencing it.

**Closed by jaredlll08** 2024-01-03 20:32 UTC
