### ISSUE TITLE
Request: Upload to Modrinth

### ISSUE THREAD

**Issue by armuell** [jaredlll08/Controlling#134] opened 2023-01-27 01:38 UTC
https://modrinth.com/

Ideally all of the mods in my pack would pull from modrinth and this mod is one of the last ones that is still CF only

**Comment by jaredlll08** [comment] 2023-01-27 01:45
duplicate of https://github.com/jaredlll08/Controlling/issues/104

**Closed by jaredlll08** 2023-01-27 01:45 UTC

**Comment by jaredlll08** [comment] 2023-06-10 00:06
https://modrinth.com/user/jaredlll08
